genomic-medicine-sweden/Twist_Solid

config/config.yaml, workflow/rules/common.smk, workflow/rules/result_files.smk
Bedtools region added
Reworked common output files
=> Bedtools region

.tests/integration/config/config.yaml, config/config.yaml, workflow/rules/common.smk, workflow/schemas/singularity.schema.yaml
=> feat: make it possible to validate that expected singularity containers are used

workflow/rules/common.smk
=> fix: copy correct gvcf output

config/config.yaml
=> fix: merge vcf without merging regions

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> feat: feature request template

config/config.yaml
=> feat: new svdb database

Jenkinsfile
=> fix: update jenkins to work with server config

.tests/release/config.yaml
=> fix: update config file used by jenkins event

config/config.yaml
=> fix: multiqc config path

.tests/jenkins/Jenkinsfile
=> fix: update jenkins path

.tests/integration/config/config.yaml, config/config.yaml, workflow/Snakefile, workflow/rules/common.smk
=> feat: added Arriba images

.github/workflows/lint.yaml, .github/workflows/snakemake-dry-run.yaml, workflow/rules/common.smk
=> feat: improve config handling

config/config.yaml, profiles/uppsala/config.yaml
=> feat: new bed file with fusion genes split into introns and exons

.github/workflows/lint.yaml, .github/workflows/pycodestyle.yaml, .github/workflows/pytest.yaml, .gitignore, .tests/units/test_cnv_report.py, .tests/units/vcf/test.cnv.vcf, workflow/Snakefile, workflow/env/cnv_tsv_report.yaml, workflow/rules/cnv_tsv_report.smk, workflow/rules/common.smk, workflow/schemas/config.schema.yaml, workflow/schemas/resources.schema.yaml, workflow/scripts/cnv_report.py
=> feat: rule used to generate cnv report file

workflow/scripts/cnv_report.py
=> fix: remove breaking import event

.tests/integration/config/config.yaml, config/config.yaml, workflow/Snakefile, workflow/rules/common.smk
=> feat: added multiqc measures to multiQC report

config/config.yaml, config/config_hard_filter_uppsala.yaml, config/config_soft_filter_uppsala.yaml, workflow/Snakefile, workflow/rules/common.smk
=> feat: filter that removes intronic variants

.tests/integration/config/config.yaml, config/config.yaml, config/config_hard_filter_germline.yaml, config/config_hard_filter_uppsala.yaml, config/config_soft_filter_uppsala.yaml, workflow/Snakefile, workflow/rules/common.smk, workflow/schemas/config.schema.yaml
=> Germline vcf

workflow/schemas/singularity.schema.yaml
=> fix: rm germline_vcf

config/config.yaml, workflow/Snakefile
=> feat: use picard lenient validation of headers

config/hotspot_report.yaml, requirements.txt, workflow/rules/common.smk
=> feat: updated output formatting in hotspot

config/config_hard_filter_germline.yaml
=> fix: germline vcf filter greater than sign in wrong direction

workflow/rules/common.smk
=> fix: dna result files overwritten by rna

.tests/jenkins/profile/config.yaml
=> feat: start using configfile argument

config/config.yaml
=> feat: run genefuse only on genes in fusion design

config/config_hard_filter.yaml, config/config_hard_filter_uppsala.yaml, config/config_soft_filter.yaml, config/config_soft_filter_uppsala.yaml
=> fix: changed COSMIC ids

workflow/rules/hotspot_info.smk, workflow/rules/hotspot_report.smk, workflow/rules/report_fusions.smk
=> refactor: sort resources

.tests/integration/config/config.yaml, config/config.yaml, workflow/env/cnv_tsv_report.yaml, workflow/env/exon_skipping.yaml, workflow/env/hotspot_info.yaml, workflow/env/hotspot_report.yaml, workflow/env/house_keeping_gene_coverage.yaml
=> feat: update hydra-genetic versions

workflow/env/cnv_tsv_report.yaml, workflow/env/exon_skipping.yaml, workflow/env/hotspot_info.yaml, workflow/env/hotspot_report.yaml, workflow/env/house_keeping_gene_coverage.yaml
=> fix: update hydra-genetics version

config/config.yaml
=> feat: Improve background

.tests/units/test_cnv_report.py, workflow/scripts/cnv_report.py
=> feat: add cnv AF

workflow/scripts/report_gene_fuse.py
=> feat: use gene pairs to filter fp fusions

config/config_hard_filter_cnv_loh.yaml
=> feat: loh hardfilter levels updated

workflow/scripts/report_fusions.py
=> fix: removed unused header columns

workflow/rules/bcftools.smk
=> Snp id fix

config/config.yaml, config/multiqc_config_dna.yaml
=> Design interval exon only

workflow/rules/common.smk
=> feat: removed redundant result files

config/config.yaml
=> feat: update tmb corrections and DP limit

config/config.yaml
=> fix: update to newer version of common

config/config.yaml
=> feat(config): update to new version of common

.github/workflows/conventional-prs.yml
=> feat(ci): add workflow for semantic commits

.github/workflows/conventional-prs.yml, config/config.yaml, config/hotspot_report.yaml, requirements.txt, workflow/envs/hotspot_report.yaml, workflow/rules/common.smk
=> feat(config): update hotspot report config and snakemake version

config/config.yaml, workflow/schemas/singularity.schema.yaml
=> refactor(config): gatkcnv use hydra docker

workflow/Snakefile
=> fix(snakemake): update hydra module versions for annotation and fusions

workflow/schemas/singularity.schema.yaml
=> refactor(schema): remove unsused rule freebayes

workflow/rules/common.smk
=> refactor(common): renamed hotspot resultfile to coverage_and_mutations

config/config.yaml, workflow/schemas/singularity.schema.yaml
=> feat(config): change cnvkit image to hydragenetics version

config/config_hard_filter_cnv_loh.yaml
=> feat(config): updated loh limit from 1.2 to 1.4

.tests/units/test_cnv_report.py, config/config.yaml, workflow/rules/cnv_tsv_report.smk, workflow/schemas/config.schema.yaml, workflow/scripts/cnv_report.py
=> feat(script): Added reporting of 1p19q LoH

config/config.yaml
=> refactor(config): added default parameters for fastp

config/config.yaml, workflow/schemas/singularity.schema.yaml
=> feat(config): change to hydragenetics vardict container

config/config.yaml, workflow/schemas/singularity.schema.yaml
=> feat(config): start using manta image from hydragenetics repo

config/config.yaml, workflow/schemas/singularity.schema.yaml
=> feat(config): change to hydragenetics bcbio-vc container

config/config.yaml, workflow/schemas/singularity.schema.yaml
=> feat(config): change to hydragenetics fusioncatcher container

config/config.yaml, workflow/schemas/singularity.schema.yaml
=> feat(config): use star-fusion from hydra-genetics

workflow/rules/hotspot_report.smk
=> feat(rule): use filtered vcf as input

workflow/Snakefile
=> fix(logfiles): log and benchmark written to same dir as output

workflow/Snakefile
=> fix(Snakemake): corrected tag

config/config.yaml, config/hotspot_report.yaml
=> feat(config): change ok level from 300 to 200 for mutations and coverage

config/config.yaml
=> feat(manta): run targeted manta

config/config.yaml
=> feat(config): decreased limit for 1p19q

.tests/integration/config/config.yaml, .tests/integration/reference/filter_fusions.csv, config/config.yaml, workflow/rules/report_gene_fuse.smk, workflow/schemas/config.schema.yaml, workflow/scripts/report_gene_fuse.py
=> feat: Gene fuse configurable

workflow/schemas/singularity.schema.yaml
=> feat(schema): set which version of default container that must be used

config/config.yaml
=> fix(config): bed files that include all hotspots

workflow/scripts/exon_skipping.py
=> fix(script): rm extra chr in chromosomes in exon skipping

.tests/integration/config/config.yaml, config/config.yaml, workflow/schemas/singularity.schema.yaml
=> fix(config): update common container to work with cnv visualization

.tests/jenkins/Jenkinsfile
=> fix(jenkins): keep files on failure

config/config.yaml, config/multiqc_config_dna.yaml, workflow/Snakefile, workflow/rules/common.smk
=> feat(multiqc): added contamination to multiqc

config/config.yaml
=> fix(config): update config to match new cnv_sv release for manta config

workflow/schemas/singularity.schema.yaml
=> fix(schema): update to match new config

workflow/schemas/singularity.schema.yaml
=> fix(schema): update required field in singularity

.tests/jenkins/test_input_VAL2022.tsv
=> fix: match new region filtered manta results

.tests/jenkins/test_input_VAL2022.tsv
=> fix: match new hrd values

config/config.yaml
=> feat: add three fusion partners to gene_fuse

workflow/Snakefile
=> feat: bump up cnv_sv version to v0.2.0

config/resources.yaml
=> fix: increased memory for all multi-threaded jobs

config/config.yaml
=> feat: added ERG to genefuse

workflow/scripts/report_fusions.py
=> feat: added total supporting reads to fusion report

workflow/scripts/exon_skipping.py, workflow/scripts/report_fusions.py
=> fix: EGFR exon skipping

.github/workflows/lint.yaml, workflow/rules/exon_skipping.smk, workflow/scripts/exon_skipping.py
=> fix: changed SJ input file to exon skipping

workflow/scripts/cnv_report.py
=> fix: gatk_cnv to gatk

.github/workflows/pycodestyle.yaml, .github/workflows/snakemake-dry-run.yaml
=> ci: fixed ubuntu and mamba versions

config/cnv_report_template.html
This PR adds gridlines to the genome view in the CNV report.
=> feat: add gridlines to genome view

.github/workflows/pycodestyle.yaml
removed conda since it's not used and break the workflow
=> ci(env): fix pycodestyle integration test

config/output_list.json
=> feat: added purecn tc estimation to results

.github/workflows/pycodestyle.yaml, .github/workflows/snakemake-dry-run.yaml
=> ci(pycodestyle): change back to ubuntu latest

workflow/Snakefile
=> feat: update version for cnv_sv module

workflow/Snakefile
=> fix: new fusion version fixing arriba

.tests/jenkins/test_input_VAL2022.tsv, .tests/jenkins/test_input_all.tsv
=> ci(test): remove png since they contain date

.tests/jenkins/test_input_VAL2022.tsv, .tests/jenkins/test_input_all.tsv
=> ci: remove mutect bam

.tests/jenkins/test_input_VAL2022.tsv, .tests/jenkins/test_input_all.tsv
=> ci: update checksum for genfuse txt

.tests/jenkins/test_input_VAL2022.tsv, .tests/jenkins/test_input_all.tsv
=> chore: dev to master

config/config.yaml, config/config_references.yaml, workflow/scripts/report_gene_fuse.py
=> feat: Erg filtering

config/output_list.json
=> feat: change purity result file to purecn output for additional info

config/config_references.yaml, workflow/Snakefile_references.smk, workflow/schemas/config_references.schema.yaml
=> feat: update to new reference module tag

config/config.yaml
=> fix: fix incorrect annoation order of BRAF

config/resources.yaml
=> chore: set default partition to low

.gitignore, LICENSE.md, docs/citations.md, docs/contributing.md, docs/credits.md, docs/hooks.py, docs/includes/abbreviations.md, docs/index.md, docs/more_resources.md, docs/overview.md, docs/requirements.txt, docs/running.md, mkdocs.yml
=> feat: add abbreviations, license, changelog and minor test updates

.tests/integration/config/config.yaml, config/config.yaml, config/output_list.json, config/resources.yaml, workflow/Snakefile, workflow/schemas/config.schema.yaml
=> feat: added fuseq_wes rule and filtering to pipeline

workflow/schemas/samples.schema.yaml
=> docs: add missing tumor_content column to sample schema

config/config.yaml
=> refactor(config): added extra vardict parameter for clarity

docs/dna_alignment.md, docs/dna_biomarkers.md, docs/dna_cnvs.md, docs/dna_fusions.md, docs/dna_prealignment.md, docs/dna_qc.md, docs/dna_snv_indels.md, docs/includes/abbreviations.md, docs/references.md, docs/rna_exon_skipping.md, docs/rna_fusions.md, docs/rna_id_snps.md, docs/rna_qc.md
=> docs: add more links to reference page

.tests/jenkins/test_input_VAL2022.tsv
=> test: update test file to match new output

workflow/scripts/exon_skipping.py
=> feat: report only MET exon 14 and EGFRvIII

config/output_list.json, workflow/Snakefile, workflow/rules/common.smk
=> fix: copy bai files instead of creating

config/config.yaml, workflow/Snakefile
=> feat: improved tmb calculations independent of artifacts and background

.tests/jenkins/test_input_VAL2022.tsv
=> test: update test files

.tests/integration/config/config.yaml, config/config.yaml
=> fix: docker version

.tests/jenkins/resources.yaml
=> ci: update resources for jenkins

config/config.yaml
=> fix: coverage cap increased

workflow/Snakefile
=> fix: update fusions and biomarker tags

workflow/scripts/cnv_report.py
=> fix: match rule input names

workflow/scripts/cnv_report.py
=> fix: add missing parameter to call of create_tsv_report

mkdocs.yml
=> docs: add anchor links to headers

mkdocs.yml
=> docs: configure simple hook plugin and search

docs/hooks.py, docs/requirements.txt, docs/setup.md, mkdocs.yml
=> docs: display current config and resource file as a expandable section

README.md
=> docs: add readthedocs link to readme

workflow/rules/common_references.smk
=> fix: correct output name for purecn reference

.tests/integration/config/config.yaml, config/config.yaml, config/config_hard_filter_purecn.yaml, config/output_files.yaml, docs/softwares.md, workflow/Snakefile, workflow/rules/cnv_tsv_report.smk, workflow/rules/common.smk, workflow/rules/purecn_modify_vcf.smk, workflow/schemas/config.schema.yaml, workflow/schemas/resources.schema.yaml, workflow/schemas/rules.schema.yaml
Use improved purecn to estimate TC. If estimated TC > 30% use this in reports otherwise use estimation from pathology.
=> feat: use germline vcf for purecn

.tests/units/test_cnv_report.py, config/config_hard_filter_cnv_loh.yaml, workflow/scripts/cnv_report.py
=> fix: Loh filtering

docs/dna_cnvs.md
=> docs: updated cnv documentation

config/config.yaml, workflow/Snakefile, workflow/rules/common.smk
=> feat: added picard mark duplicates of bam-files for QC

docs/dna_alignment.md, docs/dna_biomarkers.md, docs/dna_cnvs.md, docs/dna_fusions.md, docs/dna_prealignment.md, docs/dna_qc.md, docs/dna_snv_indels.md, docs/rna_fusions.md, docs/rna_qc.md
=> docs: update readthedocs links

.github/workflows/release-please.yaml
=> ci: update package name

workflow/Snakefile
=> fix: keep bai files

workflow/Snakefile
=> fix: added modified input function to cnv_html_report to fix notemp bug

workflow/Snakefile
=> feat: update reports module to v0.2.0

config/config.yaml, workflow/Snakefile
=> feat: tmb two noisy genes filtered

.tests/jenkins/test_input_all.tsv
=> test: updated md5 sums for tmb

workflow/Snakefile_references.smk
hard coded genomic build version has been removed from reference files created file names
=> fix: match output result from reference module

config/config.yaml
=> fix: adopt to breaking change in vep rule

config/config.yaml, requirements.txt, workflow/schemas/singularity.schema.yaml
=> feat: Update common container

.tests/integration/units.tsv, config/output_files.yaml, workflow/Snakefile
=> fix: Update snakemake

config/output_files.yaml
=> fix: reinstate output vcf file

config/config.yaml
=> feat: 2 new TERT positions added to report

config/resources.yaml
=> fix: increased star_fusions wall time

config/config.data.hg19.yaml, config/config.yaml, config/references/design_files.hg19.yaml
=> fix: clean config file

config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/config.yaml, workflow/rules/report_fusions.smk, workflow/scripts/report_fusions.py
=> feat: Fusion report filtering

workflow/scripts/report_fusions.py
=> fix: support header with fusions filtering

config/config.data.hg19.yaml
=> fix: new rna fusion filter file without duplicate entry and header

workflow/rules/report_fusions.smk
=> refactor: remove unused entry

workflow/rules/common_references.smk
=> fix: change from svdb_query file to svdb_merge file

config/config.data.hg19.yaml
=> feat: add blacklist for fuseq_wes filtering

profiles/uppsala_ref/config.yaml, workflow/Snakefile_references.smk
=> fix: configs for reference profile

config/config.yaml
=> fix: remove unused time consuming step in fusioncatcher

workflow/rules/common.smk
=> fix: remove newline after purity in cnvkit_call command

config/config.yaml, config/filters/config_hard_filter_umi_vep105.yaml, config/filters/config_soft_filter_umi_vep105.yaml, config/output_files.yaml, requirements.txt
=> feat: added umi vcf filters

requirements.txt, workflow/rules/report_fusions.smk, workflow/scripts/report_fusions.py
=> feat: restructured rna fusion report for improved interpretation

config/output_files.yaml, workflow/Snakefile
=> feat: new outputfile structure based on sample

config/output_files.yaml
=> fix: corrected results path for soft-filtered umi vcf

config/output_files.yaml
=> fix: remove extra sample folder in output

workflow/rules/hotspot_report.smk
=> fix: added missing double mutations to report

requirements.txt
=> feat: update hydra-genetics version

.tests/jenkins/Jenkinsfile
=> ci: update to match latest jenkins setup

.tests/jenkins/Jenkinsfile
=> ci: update jenkins file

.tests/jenkins/Jenkinsfile
=> ci: update python version

.tests/jenkins/Jenkinsfile
=> ci: use system nextflow installation

.tests/jenkins/Jenkinsfile
=> ci: update ci environment

.tests/jenkins/Jenkinsfile, .tests/jenkins/profile/config.yaml
=> ci: minor changes to jenkins file

.tests/jenkins/Jenkinsfile
=> ci: minor change to develop stage

.tests/integration/config/config.yaml, config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/config.yaml, config/config_references.yaml, config/config_references_hg38.yaml, workflow/schemas/config.schema.yaml
=> feat: data config for HG38 (missing HRD, SVDB, purecn)

config/filters/config_soft_filter_umi_vep105.yaml, requirements.txt
=> fix: avoid clash with earlier filter annotation

config/filters/config_hard_filter_umi_vep105.yaml, config/filters/config_soft_filter_umi_vep105.yaml
=> fix: rm dangerous qual filter form umi

requirements.txt, workflow/rules/common.smk
=> feat: print pipeline and software version and config to results

.tests/jenkins/test_input_main.tsv
=> ci: minor updates to match jenkins server result

.github/workflows/lint.yaml, requirements.txt, workflow/env/copy_result.yaml, workflow/rules/common.smk
=> fix: remove unused library that break requirements

.tests/jenkins/test_input_main.tsv
=> ci: revert a few checksum for master

.tests/jenkins/test_input_main.tsv
=> ci: minor update to checksum

config/reports/hotspot_report.yaml
=> fix: add "_" to regexp so that indels are reported correctly

config/config.yaml
=> fix: add implied msi configuration from module to config

config/references/design_files.hg19.yaml, config/references/design_files.hg38.yaml
=> feat: updated with new reference files

config/config.data.hg19.yaml, config/config.data.hg38.yaml
=> feat: two new amplification genes reported

config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/config.yaml
=> refactor: move chrom arm file

config/references/design_files.hg38.yaml
=> fix: update hg38 ref files, point to correct release

workflow/scripts/cnv_report.py
=> fix: rm duplicate entries of cnv in report

config/config.data.hg19.yaml
=> fix: update config, merge_cnv_json, to use latest amp gene bed file

.tests/jenkins/test_input_develop.tsv
=> ci: update test file

.tests/jenkins/test_input_develop.tsv
=> test: update cnv deletion results for validation

config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/references/nextseq.hg19.pon.yaml, config/references/nextseq.hg38.pon.yaml, config/references/novaseq.hg19.pon.yaml
=> feat: new PoN on figshare

.tests/integration/config/config.yaml, config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/output_files.yaml, config/references/design_files.hg19.yaml, config/references/design_files.hg38.yaml, config/reports/multiqc_config_dna.yaml, workflow/rules/hotspot_report.smk, workflow/schemas/config.schema.yaml, workflow/schemas/rules.schema.yaml
=> feat: add hotspot file for ENC

requirements.txt, workflow/rules/common.smk
=> feat: update hydra version

docs/run_on_restricted_system_env.md
=> docs: do not activate python env

config/references/design_files.hg38.yaml, config/references/novaseq.hg19.pon.yaml
=> fix: correct reference files

.tests/jenkins/Jenkinsfile
=> ci: make jenkins fetch design and pon files

config/config.yaml, workflow/schemas/singularity.schema.yaml
=> feat: update common container to new hydra

config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/references/design_files.hg19.yaml, config/references/design_files.hg38.yaml
=> fix: update ENC hotspots

.tests/jenkins/test_input_develop.tsv, .tests/jenkins/test_input_main.tsv, config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/config.yaml, config/output_files.yaml, config/resources.yaml, docs/dna_fusions.md, docs/softwares.md, workflow/Snakefile, workflow/rules/report_gene_fuse.smk, workflow/schemas/config.schema.yaml, workflow/schemas/resources.schema.yaml, workflow/schemas/rules.schema.yaml, workflow/scripts/report_gene_fuse.py
=> feat: fusion calling for cfDNA

.tests/jenkins/test_input_develop.tsv
=> test: corrected develop cov_and_mut md5sums

.tests/integration/DATA/centromeres.bed, .tests/integration/config/config.yaml, config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/config.yaml, config/references/design_files.hg19.yaml, config/references/design_files.hg38.yaml, workflow/Snakefile
=> feat: add cytobands to cnv report

config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/references/design_files.hg19.yaml, config/references/design_files.hg38.yaml
=> feat: rm noisy MUC6 from cnv VAF plot

config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/references/design_files.hg19.yaml, config/references/design_files.hg38.yaml
=> feat: rm CDH1 from reporting of cnv deletions

config/config.yaml, config/reports/multiqc_config_dna.yaml, config/reports/multiqc_config_rna.yaml, workflow/Snakefile, workflow/schemas/singularity.schema.yaml
=> feat: updated multiqc for version info

docs/result_files.md
=> docs: corrected purecn documentation

workflow/scripts/sample_mixup_check.py
=> fix: handle missing ID-SNPs

config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/references/design_files.hg19.yaml, config/references/design_files.hg38.yaml
=> feat: updated ENC hotspot files

config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/references/design_files.hg19.yaml, config/references/design_files.hg38.yaml, workflow/scripts/report_fusions.py
=> feat: AF rna fusion filter possibility

config/reports/multiqc_config_rna.yaml
=> fix: update rna multiqc report for new version of multiqc

workflow/scripts/report_fusions.py
=> fix: FusionCatcher liftover fail crashes report

workflow/Snakefile, workflow/scripts/report_fusions.py
=> refactor: cleanup code

config/reports/multiqc_config_rna.yaml
=> fix: rm insert size from rna multiqc

workflow/Snakefile
=> chore: update to released versions of modules

.tests/jenkins/test_input_main.tsv
=> test: update of md5sums for jenkins

.tests/jenkins/test_input_main.tsv, workflow/Snakefile
=> chore: dev to master (correct md5sums)

workflow/scripts/cnv_report.py
=> fix: correction of output text for 1p19q

workflow/Snakefile
=> fix: update cnv_sv module

config/reports/multiqc_config_dna.yaml, config/reports/multiqc_config_rna.yaml
=> fix: Multiqc rna

workflow/scripts/sample_mixup_check.py
=> fix: sample mixup in percentage

workflow/scripts/report_fusions.py
=> fix(report_fusion): fix div by zero

workflow/Snakefile_references.smk
=> fix(cnvkit_batch): fix input variable name to match wrapper

.github/CODEOWNERS
=> chore: add Monika as code owner

config/config.yaml
=> chore(config.yaml): "sum" af of complex variants

config/config.data.hg19.yaml, config/config.data.hg38.yaml
=> fix(jumble): Update config.data.hg19.yaml

workflow/scripts/sample_mixup_check.py
=> fix(sample_mixup): cut_off adjusted to percent

config/output_reference_files.yaml, workflow/Snakefile_references.smk
=> fix: correct MSIsensorpro output

config/config.data.hg19.yaml, config/config.yaml, config/output_files.yaml, config/resources.yaml, workflow/Snakefile
=> feat: added the Juli caller

workflow/Snakefile
=> fix(juli): update fusion module

.tests/integration/config/config.yaml, config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/output_files.yaml, workflow/Snakefile, workflow/schemas/config.schema.yaml, workflow/schemas/config_references.schema.yaml
=> feat: MSI filtering

config/output_files.yaml
=> feat: save the germline vcf used in CNV analysis in results

.tests/integration/config/config.yaml, config/config.yaml, config/reports/general_report.yaml, workflow/Snakefile, workflow/templates/cnv_html_report/style.css
=> feat: add general report

workflow/Snakefile
=> fix(msi): correct unfiltered msi output folder

config/reports/multiqc_config_dna.yaml
=> fix(MultiQC): remove extra lines in MultiQC DNA report

config/references/references.hg19.yaml
=> fix(references.hg19.yaml): JuLI ref-files

.tests/jenkins/resources.yaml
=> chore(resources.yaml): Extra resources juli_caller on jenkins

.tests/jenkins/test_input_develop.tsv
=> fix(test_input_develop.tsv): Update sums

docs/dna_cnvs.md, docs/dna_snv_indels.md, docs/running.md, docs/setup.md
=> docs: broken links

config/output_files.yaml
=> fix(hla): Correct results folder structure for HLA calling files

config/reports/multiqc_config_dna.yaml
=> fix: one row per sample in MultiQC report

.tests/jenkins/test_input_develop.tsv
=> fix(test_input_develop.tsv): Remove id_snps dev

.tests/jenkins/test_input_develop.tsv
=> fix(test_input_develop.tsv): rm sample mix-up dev

.tests/jenkins/Jenkinsfile
Re-run incomplete processes when a pipeline is re-started during integration testing. 
Added --rerun-incomplete to snakemake command in both develop and main integration test.
=> chore(Jenkinsfile): Run test with rerun-incomplete

.tests/jenkins/profile/config.yaml
=> test: Update config.yaml

config/config.yaml, config/output_files.yaml, config/reports/general_report.yaml
=> fix: General report improvements Lotte

workflow/scripts/cnv_report.py
=> fix: remove potential duplicate and missed output of 1p19q

config/resources.yaml
=> fix: increase wall time for juli

config/reports/multiqc_config_dna.yaml, config/reports/multiqc_config_rna.yaml, profiles/slurm/config.yaml, profiles/uppsala/config.yaml
=> feat(MultiQC): enable setting contact info using ENV

config/config.data.ctdna.hg19.yaml, config/filters/config_hard_filter_umi_vep105.yaml, config/filters/config_soft_filter_umi_vep105.yaml, config/references/design_files.hg19.yaml, config/references/nextseq.hg19.pon.yaml, profiles/slurm_ctDNA/config.yaml
=> feat: ctdna config

config/output_files.yaml, workflow/Snakefile
=> fix: msi is calculated without umi

.tests/jenkins/test_input_develop.tsv, config/config.data.hg19.yaml, config/config.yaml, workflow/Snakefile
=> feat: improved TMB for ctdna

workflow/Snakefile
=> fix: update tmb_umi rule to match biomarker module

.tests/units/vcf/test.deletions.tsv, workflow/scripts/cnv_report.py
=> fix: adapt script to new header

workflow/Snakefile
=> fix: update reports module to fix email import in general report

docs/dna_biomarkers.md
=> docs: fix link to msisensorpro

docs/running.md
Thank-you for such clear instructions, I found one very small issue, and figured I'd report it back!
=> chore: fix virtual environment activate path

config/filters/config_hard_filter_umi_vep105.yaml, config/filters/config_soft_filter_umi_vep105.yaml
=> fix: update ctDNA artifact filtering of INDELs

config/references/nextseq.hg19.pon.yaml, workflow/Snakefile_references.smk
=> fix: update reference module with new artifact reference

workflow/scripts/estimate_ctDNA_fraction.py
=> fix(estimate_ctDNA_fraction.py): bugfix in extra snv output info

config/filters/config_hard_filter_umi_vep105.yaml, config/filters/config_soft_filter_umi_vep105.yaml
=> fix: new artifact filter need lower SD artifact rescue in umi

workflow/scripts/call_small_cnv_amplifications.py
=> fix: update amplification headers

config/output_files.yaml
=> fix: only run FuseqWES for FFPE-analys

config/config.data.ctdna.hg19.yaml, config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/config.yaml, config/output_files.yaml, config/reports/general_report.umi.yaml, workflow/Snakefile
=> feat: general report adapted for ctdna workflow

.tests/units/vcf/test.amplifications.tsv, workflow/scripts/cnv_report.py
=> fix: adapt to new small amplification header

workflow/Snakefile
=> feat: update reports module and add pipeline name

config/references/design_files.hg19.yaml, config/references/nextseq.hg19.pon.yaml
=> fix: update figshare links

workflow/Snakefile
=> fix: bug in Snakefile for umi general report

requirements.txt
=> fix: Add scipy which is needed by ctDNA_fraction_estimation

workflow/scripts/estimate_ctDNA_fraction.py
=> fix(estimate_ctDNA_fraction.py): median of empty list

requirements.txt
=> fix(requirements.txt): Added requirement pyaml-env

config/config.yaml
=> fix: general report moved one folder up

workflow/Snakefile
=> fix: update cnv_sv module to fix jumble cpu overusage

workflow/Snakefile
=> fix: update reports module to fix cnv html report table bug

config/config.data.hg19.yaml, config/config.data.hg38.yaml, config/config.yaml, config/filters/config_hard_filter_scanitd.yaml, config/output_files.yaml, config/references/design_files.hg19.yaml, config/references/design_files.hg38.yaml, config/reports/general_report.umi.yaml, config/reports/general_report.yaml, workflow/Snakefile
=> feat: added scanITD for ITD calling of selected genes

config/config.yaml, workflow/schemas/singularity.schema.yaml
Added scipy and updated software versions
=> feat: new common container

workflow/Snakefile
=> fix: remove samtools sorting step where not needed

.tests/jenkins/test_input_develop.tsv, config/config.yaml, workflow/Snakefile, workflow/rules/common.smk
=> feat: added seqtk subsampling option

config/references/design_files.hg19.yaml
=> fix: corrected uro file

.tests/jenkins/test_input_main.tsv
=> test: update id-snp in main

workflow/Snakefile
=> fix: sort umi bam files by QNAME

config/config.data.hg38.yaml
=> fix: juli hg19 to hg38

config/references/design_files.hg19.yaml
=> fix: reference files

.tests/jenkins/test_input_develop.tsv
=> fix: update mod cov and mut files
