genomic-medicine-sweden/Twist_Solid

config/cnv_report_template.html
requirements.txt
workflow/rules/cnv_html_report.smk
workflow/scripts/cnv_json.py

This PR adds a results table to the CNV HTML report. It only shows results from the caller that has been selected on the top of the page. A user can visualise a certain region by clicking the magnifying glass on the corresponding row.

feat: add results table to CNV report

---

config/cnv_report_template.html

The underlying data was there, but if one of the datasets was empty, it still tried to get the header information. Now we check if there is data available and set an appropriate message if not.

fix: problem with empty CNV table

---

config/cnv_report_template.html

This PR adds a print layout to the CNV report. Page breaks now seem to make better sense than they did before, and I also hid some text that doesn't make sense for a printed version of the report.

feat: create print layout for the CNV HTML report

---

config/cnv_report_template.html
config/config.yaml
workflow/rules/cnv_html_report.smk
workflow/rules/common.smk
workflow/schemas/config.schema.yaml
workflow/scripts/cnv_html_report.py
workflow/scripts/merge_json.py

This PR modifies the results table in the HTML report to only show a filtered set of CNVs. The configuration works by defining what combinations of annotations and filters to use. For example, the configuration below would look for two VCF files, one annotated according to the `cnv_loh_genes` tag and filtered according to `cnv_hard_filter_loh`, and the other annotated with the `cnv_amp_genes` tag and filtered with `cnv_hard_filter_amp`.
```yaml
cnv_html_report:
template: "config/cnv_report_template.html"
cnv_vcf:
- annotation: cnv_loh_genes
filter: cnv_hard_filter_loh
- annotation: cnv_amp_genes
filter: cnv_hard_filter_amp
template: config/cnv_report_template.html
```
If `cnv_vcf` doesn't exist, or is empty, the results table in the report will not be generated.
The bug where copy numbers …

feat: only show filtered CNVs in the report

---

config/cnv_report_template.html

This PR adds a simple toggle zoom for the y-axis of the log ratios in the chromosome plot. The default range with the checkbox unchecked is [-2, 2], and if there are data points outside this range, a warning is shown. If the checkbox is checked, the y-axis is scaled to the extent of the data.

feat: y-axis zoom in chromosome plot

---

config/cnv_report_template.html

This PR fixes an issue when there are no results to display in the table. Now a proper message is shown if the table is supposed to be empty.
I know I tested this behaviour at some point before, but it must have become out of sync with all the other restructuring going on.

fix: empty table in CNV report not initialised correctly

---

config/cnv_report_template.html
workflow/rules/cnv_html_report.smk
workflow/rules/common.smk
workflow/scripts/cnv_html_report.py

This PR adds the tumor cell content and the method used to obtain it to the CNV report. For this, I more or less copied the `get_tc` function from the cnv_sv module. When the report eventually is moved to the cnv_sv module, this function can be removed, together with a bunch of other things in `common.smk`.

feat: add tumor cell content to report

---

config/cnv_report_template.html
workflow/scripts/merge_json.py

This PR adds the BAF values from the CNV VCF files. In addition, the column names have been improved with proper capitalisation.
An information message regarding strange BAF values was also added:

feat: add BAF to CNV table

---

config/cnv_report_template.html
workflow/scripts/merge_json.py

This PR adds a checkbox to the CNV HTML report that toggles filtering of the variants. The filter is enabled by default. When applying the filter, COPY_NORMAL variants might still show up in the table, and the reason for this is that a variant from another caller covering the same gene passed the filter. A note explaining this has also been added.

feat: toggle filtering of CNV table

---

config/config.yaml

When cnvkit finds regions with really low coverage in tumors, this is almost always due to sequencing errors or probe failure.  The option --drop-low-coverage removes regions with under -15 in log2ratio. This will solve the outliers that sometimes appear in our plots. https://cnvkit.readthedocs.io/en/stable/tumor.html

feat: drop low coverage

---

config/config.yaml
config/resources.yaml
requirements.txt
workflow/Snakefile
workflow/rules/common.smk

feat: RNA trimming for arriba

---

config/config.yaml
workflow/Snakefile

feat: use v0.1.0 of fusion module to filter FP Fuseq_WES calls

---

workflow/Snakefile

This error was at first not apparent since whether or not it manifested itself depended on how the rule graph was resolved. Now the report should never be generated before all required files are available.

fix: correct paths for CNV report extra tables

---

workflow/rules/common_references.smk

In the reference pipeline:
This fixes when there are samples in units.tsv that are missing in samples.tsv. It also fixes when there is no outputfiles for a output using a log message instead of an error.

fix: handle missing files better

---

.tests/jenkins/test_input_develop.tsv

the result for one variant and the f1f2 field differs when you run the analysis on marvin and jenkins. Unknown why, but this new checksum will make sure that the test passes on jenkins.

ci: update test file for jenkins

---

config/config.yaml

Some GATK CNV results are missing from the table as they where merged with CNVkit results. This will mitigate this.

feat: do not merge regions that are not identical

---

workflow/rules/common.smk

fix: bugfix of version crash when pipeline runs over several days

---

config/config.yaml
workflow/rules/bcftools.smk
workflow/rules/sample_mixup_check.smk
workflow/schemas/config.schema.yaml
workflow/scripts/sample_mixup_check.py

feat: make sample_mixup_configurable

---

config/output_reference_files.yaml
workflow/rules/common_references.smk

The output from Jumble_reference is dependent on the design file used. This fixes so that the output file name is collected from the config file used and not have to be hardcoded and changed when the design bed is updated. 
It also fixes the integration tests which has a different name of design bed file.

fix: jumble output is dependent on design bed name

---

workflow/Snakefile
workflow/Snakefile_references.smk

New version of module snv_indels.
Added: Python script for handling complex variants with several vcf records.
Some variant callers (e.g. vardict) will compose variants within close physical distance and report it as one complex variant. vt_decompose will separate these complex variants into separate records. However, during decomposition the same allele might be reported in several records, one originating from the single variant and one or more records reported from one or more complex variants, even if these records are corresponding to the same allele at the same position. The allele frequencies will also be different for these records since it might be derived from the frequency of the allele in combination with a specific allele at another position whithin the complex variant.
This …

feat: Handling complex variants in snv_indel

---

config/filters/config_hard_filter_cnv_loh.yaml

Jumble does not report BAF-values. So when we filter on BAF-values the CNV calls will not be filtered due to NA-handling returns false by default. The NA-handling is now set to True for the BAF-values to fix this.

fix(jumble): NA-handling set to True for missing BAF values

---

workflow/Snakefile

The use of temporary files in purecn breaks the report-generation. This is now fixed.

fix(Snakefile): No temporary files in purecn out

---

config/references/design_files.hg19.yaml

Fixed: Updating figshare links for ctDNA reference files.

fix: update additional figshare links
